---
- name: 安装 Jenkins 到虚拟机
  hosts: jenkins_cluster
  gather_facts: yes
  become: yes
  roles:
    - install-jenkins

  vars:
    # 覆盖默认配置（可选）
    # jenkins_http_port: 8080
    # jenkins_java_options: "-Djava.awt.headless=true -Xmx2g -Xms512m"
